name: Generate & Push SDKs

on:
  push:
    paths:
      - 'openapi/tickcatcher.yaml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using deploy key
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate SDKs
        run: bash build.sh

      - name: Commit SDKs
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add -f typescript/* python/* swift/* kotlin/* go/* csharp/* rust/*
          git commit -m "Regenerated SDKs [skip ci]" || echo "No changes to commit"

      - name: Push SDKs
        run: git push origin main
